[package]
name    = "flock"
version = "0.1.0"

authors = ["Zachary Kohnen <z.kohnen@aeroteameindhoven.nl>"]
edition = "2021"
publish = false

[profile.dev.package."*"]
opt-level = 2

[dependencies]
eframe = "0.22.0"
ffmpeg-next = "6.0.0"
ffmpeg-sidecar = "0.4.1"
nix = { version = "0.26.2", default-features = false, features = ["signal", "process"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17" }
video-rs = { version = "0.4.0", features = ["ndarray"] }
