[package]
name    = "flock"
version = "0.1.0"

authors = ["Zachary Kohnen <z.kohnen@aeroteameindhoven.nl>"]
edition = "2021"
publish = false

[dependencies]
eframe = "0.22.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17" }
